"""Initial migration

Revision ID: 26816f12cdcc
Revises: 
Create Date: 2026-09-19 03:51:28.123540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26816f12cdcc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bartenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bartenders_id'), 'bartenders', ['id'], unique=False)
    op.create_index(op.f('ix_bartenders_name'), 'bartenders', ['name'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decks_id'), 'decks', ['id'], unique=False)
    op.create_index(op.f('ix_decks_name'), 'decks', ['name'], unique=True)
    op.create_table('officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_officers_id'), 'officers', ['id'], unique=False)
    op.create_index(op.f('ix_officers_name'), 'officers', ['name'], unique=True)
    op.create_table('cruise_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('boarding_time', sa.DateTime(), nullable=True),
    sa.Column('actual_boarding', sa.DateTime(), nullable=True),
    sa.Column('actual_departure', sa.DateTime(), nullable=True),
    sa.Column('guest_count', sa.Integer(), nullable=True),
    sa.Column('water_taxi', sa.Integer(), nullable=True),
    sa.Column('extra_time', sa.Time(), nullable=True),
    sa.Column('weather', sa.String(), nullable=True),
    sa.Column('function_type', sa.String(), nullable=True),
    sa.Column('damages', sa.Text(), nullable=True),
    sa.Column('floor_plan_followed', sa.Boolean(), nullable=True),
    sa.Column('dj', sa.String(), nullable=True),
    sa.Column('dj_feedback', sa.Text(), nullable=True),
    sa.Column('lost_and_found', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('food_explain', sa.Text(), nullable=True),
    sa.Column('other', sa.Text(), nullable=True),
    sa.Column('source_filename', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cruise_events_id'), 'cruise_events', ['id'], unique=False)
    op.create_table('registers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registers_id'), 'registers', ['id'], unique=False)
    op.create_index(op.f('ix_registers_name'), 'registers', ['name'], unique=True)
    op.create_table('bar_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('bartender_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('gross_sales', sa.Float(), nullable=True),
    sa.Column('house_sales', sa.Float(), nullable=True),
    sa.Column('ticket_sales', sa.Float(), nullable=True),
    sa.Column('account_sales', sa.Float(), nullable=True),
    sa.Column('tip_out', sa.Float(), nullable=True),
    sa.Column('tickets_tape', sa.Integer(), nullable=True),
    sa.Column('tickets_actual', sa.Integer(), nullable=True),
    sa.Column('tickets_diff', sa.Integer(), nullable=True),
    sa.Column('alcohol_qty', sa.Integer(), nullable=True),
    sa.Column('alcohol_value', sa.Float(), nullable=True),
    sa.Column('pop_juice_qty', sa.Integer(), nullable=True),
    sa.Column('pop_juice_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['bartender_id'], ['bartenders.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['cruise_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['register_id'], ['registers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bar_summaries_id'), 'bar_summaries', ['id'], unique=False)
    op.create_table('cruise_event_officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['cruise_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cruise_event_officers_id'), 'cruise_event_officers', ['id'], unique=False)
    op.create_table('food_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('substitutions', sa.Text(), nullable=True),
    sa.Column('quality', sa.Text(), nullable=True),
    sa.Column('quantity_shortages', sa.Text(), nullable=True),
    sa.Column('presentation', sa.Text(), nullable=True),
    sa.Column('problems_praises', sa.Text(), nullable=True),
    sa.Column('other', sa.Text(), nullable=True),
    sa.Column('items_required', sa.Text(), nullable=True),
    sa.Column('completed_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['cruise_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_reports_id'), 'food_reports', ['id'], unique=False)
    op.create_table('security_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('guard_name', sa.String(), nullable=False),
    sa.Column('incident_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['cruise_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_incidents_id'), 'security_incidents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_incidents_id'), table_name='security_incidents')
    op.drop_table('security_incidents')
    op.drop_index(op.f('ix_food_reports_id'), table_name='food_reports')
    op.drop_table('food_reports')
    op.drop_index(op.f('ix_cruise_event_officers_id'), table_name='cruise_event_officers')
    op.drop_table('cruise_event_officers')
    op.drop_index(op.f('ix_bar_summaries_id'), table_name='bar_summaries')
    op.drop_table('bar_summaries')
    op.drop_index(op.f('ix_registers_name'), table_name='registers')
    op.drop_index(op.f('ix_registers_id'), table_name='registers')
    op.drop_table('registers')
    op.drop_index(op.f('ix_cruise_events_id'), table_name='cruise_events')
    op.drop_table('cruise_events')
    op.drop_index(op.f('ix_officers_name'), table_name='officers')
    op.drop_index(op.f('ix_officers_id'), table_name='officers')
    op.drop_table('officers')
    op.drop_index(op.f('ix_decks_name'), table_name='decks')
    op.drop_index(op.f('ix_decks_id'), table_name='decks')
    op.drop_table('decks')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_bartenders_name'), table_name='bartenders')
    op.drop_index(op.f('ix_bartenders_id'), table_name='bartenders')
    op.drop_table('bartenders')
    # ### end Alembic commands ###
